name: simple_cache_manager
description: "A simple cache manager for Dart. It stores the data into json and provides methods to write, read, delete and clear the cache."
version: 0.0.3
repository: https://github.com/errichamonda/simple_cache_manager

environment:
  sdk: ^3.6.0

dependencies:
  path: ^1.9.0
  safe_local_storage: ^2.0.1

dev_dependencies:
  test: ^1.25.13
  flutter_lints: ^5.0.0
